const DB_NAME='lianxibu-db', DB_VERSION=1, STORE='app';
const PLAN=[
 {id:'push',name:'推日',en:'PUSH',focus:'胸 · 肩 · 前锯肌',warmup:'轻度有氧 5 分钟；胸椎旋转、肩胛绕环、墙面滑手各 8–10 次。',items:[
  ex('db-bench','平板哑铃卧推','胸大肌 · 肱三头肌 · 三角肌前束',4,'8–12',120,'哑铃从胸部两侧推起，肘部与身体约 30–60°。','肩胛自然稳定，不要刻意夹死；下巴轻收。以每手 4–5 kg 起步，动作稳定优先。',['10 kg 小杠铃平板卧推','双侧绳索站姿推胸']),
  ex('incline-db','低角度上斜哑铃卧推','胸大肌上部 · 三角肌前束 · 肱三头肌',3,'8–12',120,'凳子调至约 15–30°，哑铃从胸两侧向上推。','不追求大角度，不耸肩；保持颈部自然。',['10 kg 小杠铃低上斜卧推','双侧低位绳索斜向推胸']),
  ex('cable-diagonal','半跪姿单臂绳索斜向推举','三角肌前束 · 前锯肌 · 肱三头肌',3,'10–12/侧',90,'滑轮调低，单膝跪地，从肩前沿前上方推出。','末端允许肩胛自然上回旋；腰不后仰，不要强行压肩。',['坐姿中立握哑铃肩推（无痛时）','单臂站姿绳索肩推']),
  ex('cable-lateral','绳索侧平举','三角肌中束',3,'12–15',75,'手臂在身体前外侧约 20–30°抬起至接近肩高。','轻重量，肩膀不靠近耳朵，脖子放松。',['哑铃侧平举','单臂靠墙哑铃侧平举']),
  ex('wall-slide','墙面滑手 + 前锯肌前伸','前锯肌 · 肩胛控制',3,'10–12',60,'前臂贴墙向上滑，末端温和向前伸展。','动作平稳，不耸肩，不追求疲劳。',['仰卧哑铃前锯肌冲拳','弹力带墙面滑手'])]},
 {id:'pull',name:'拉日',en:'PULL',focus:'背部 · 后肩 · 手臂',warmup:'轻度有氧 5 分钟；肩胛绕环与轻重量绳索热身。全程不强行沉肩夹背。',items:[
  ex('lat-pulldown','中立握高位下拉','背阔肌 · 肱二头肌',4,'8–12',120,'坐稳后将把手拉向上胸，肘部顺势向下。','躯干轻微后倾即可；颈部中立，不要耸肩或猛夹肩胛。',['单臂跪姿高位绳索下拉','弹力带下拉']),
  ex('chest-row','胸托哑铃划船','背部 · 后三角肌 · 肱二头肌',3,'8–12',120,'胸口支撑斜凳，手臂自然下垂后拉向身体两侧。','用可控轻重量；不抬头、不刻意夹背，若肩胛内侧痛加重则缩小幅度或停止。',['坐姿胸托划船机（轻阻力）','单臂绳索划船']),
  ex('cable-row','坐姿中立握绳索划船','背阔肌 · 菱形肌 · 肱二头肌',3,'10–12',90,'坐稳，手柄拉向躯干，回程允许肩胛自然向前。','避免躯干后仰借力及全程夹紧肩胛。',['单臂站姿绳索划船','弹力带划船']),
  ex('face-pull','绳索面拉（轻重量）','后三角肌 · 肩袖 · 上背',3,'12–15',75,'绳索约面部高度，拉向眉眼两侧，手肘舒适外展。','颈部放松，动作不诱发疼痛；不需要用力夹背。',['俯身哑铃反向飞鸟','弹力带拉开']),
  ex('deadbug','死虫式','腹横肌 · 核心稳定',3,'8–10/侧',60,'仰卧，交替伸展对侧手脚，腰背保持稳定。','呼吸平稳，动作范围以腰背不拱起为准。',['Pallof 抗旋转推','鸟狗式'])]},
 {id:'legs',name:'腿日',en:'LEGS',focus:'臀 · 腿 · 核心',warmup:'轻度有氧 5 分钟；徒手髋铰链、深蹲各 8–10 次。',items:[
  ex('smith-squat','史密斯深蹲','股四头肌 · 臀大肌',4,'8–12',150,'杠铃置于斜方肌中下部，双脚略在杠铃垂直线前方，下蹲至稳定深度。','不要压颈椎；颈部自然，膝盖跟随脚尖。若颈肩不适，改高脚杯深蹲。',['高脚杯深蹲','10 kg 小杠铃前蹲']),
  ex('hip-thrust','杠铃臀推','臀大肌 · 腘绳肌',4,'8–12',120,'上背靠凳，杠铃置于髋部，臀部发力抬起至躯干与大腿接近水平。','顶端不挺腰，控制下降；可用垫子保护髋部。',['史密斯臀推','哑铃臀推']),
  ex('bulgarian','保加利亚分腿蹲','股四头肌 · 臀大肌',3,'8–10/侧',120,'后脚置于矮凳，前脚站稳，垂直下蹲后推地起身。','先徒手练平衡，躯干和颈部自然。',['反向箭步蹲','前脚抬高分腿蹲']),
  ex('leg-curl','坐姿或俯卧腿弯举','腘绳肌',3,'10–15',90,'调整器械轴心与膝关节对齐，屈膝拉动滚垫。','控制回程，不用惯性。',['单腿腿弯举','哑铃夹脚俯卧腿弯举']),
  ex('pallof','Pallof 抗旋转推','腹斜肌 · 核心稳定',3,'10–12/侧',60,'滑轮置于胸口高度，侧身站立，双手将把手推至胸前远处。','骨盆保持正对前方，躯干不旋转。',['弹力带 Pallof Press','Dead Bug 死虫式'])]},
 {id:'swim',name:'游泳',en:'SWIM',focus:'蛙泳 · 约 1000 m',warmup:'按舒适速度游泳，记录距离与感受。颈部不适时降低抬头幅度或停止。',items:[ex('swim-1000','蛙泳','有氧 · 全身协调',1,'约 1000 m',0,'以轻松、可持续的节奏完成计划距离。','减少持续抬头，保持颈部舒适；若疼痛加重则停止。',['降低距离或放慢速度','改为舒适的仰泳/水中步行'])]}
];
function ex(id,name,muscles,sets,reps,rest,how,care,alts){return{id,name,muscles,sets,reps,rest,how,care,alts}}
let db, data={sessions:[],defaults:{},permanentNotes:{},active:null}, timerId, deferredInstall=null, viewMonth=new Date(), selectedDate=today();
const app=document.querySelector('#app');
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function localISO(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>req.result.createObjectStore(STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function readData(){return new Promise((resolve,reject)=>{const req=db.transaction(STORE).objectStore(STORE).get('root');req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}
function save(){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(data,'root');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function init(){try{db=await openDB();data=await readData()||data}catch(e){toast('浏览器存储暂不可用');console.error(e)}if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});window.addEventListener('hashchange',render);document.querySelector('#backupBtn').onclick=backup;document.querySelector('#importFile').onchange=importBackup;document.querySelector('#installBtn').onclick=installApp;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.querySelector('#installBtn').hidden=false});window.addEventListener('pageshow',tick);document.addEventListener('visibilitychange',tick);render()}
function latestSession(planId){return data.sessions.filter(s=>s.planId===planId&&s.status==='done').sort((a,b)=>b.date.localeCompare(a.date))[0]}
function makeSession(plan){const last=latestSession(plan.id);return{id:crypto.randomUUID(),planId:plan.id,date:today(),status:'active',startedAt:Date.now(),exercises:plan.items.map(exr=>{const old=last?.exercises.find(x=>x.id===exr.id);const n=data.defaults[exr.id]??exr.sets;return{id:exr.id,name:exr.name,sets:Array.from({length:n},(_,i)=>({weight:old?.sets[i]?.weight??'',reps:'',rir:''})),note:'',skip:false,skipReason:''}}),summary:{effort:'',pain:'',note:''},restUntil:null,restLabel:''}}
async function startWorkout(id){let s=data.sessions.find(x=>x.status==='active'&&x.planId===id);if(!s){s=makeSession(PLAN.find(x=>x.id===id));data.sessions.push(s)}data.active=s.id;await save();location.hash='#workout/'+s.id}
function current(){return data.sessions.find(s=>s.id===data.active)||data.sessions.find(s=>s.status==='active')}
function render(){const hash=location.hash||'#home';document.querySelectorAll('.tabbar a').forEach(a=>a.classList.toggle('active',hash.split('/')[0]===a.getAttribute('href')));if(hash.startsWith('#workout/'))return renderWorkout(hash.split('/')[1]);if(hash==='#calendar')return renderCalendar();if(hash==='#history')return renderHistory();if(hash==='#settings')return renderSettings();renderHome()}
function renderHome(){const days=PLAN.map(p=>{const active=data.sessions.find(s=>s.status==='active'&&s.planId===p.id),last=latestSession(p.id);return `<div class="day-card" role="button" tabindex="0" onclick="openPlan('${p.id}')" onkeydown="if(event.key==='Enter')openPlan('${p.id}')"><div class="day-top"><div><div class="day-en">${p.en}</div><div class="day-name">${p.name}</div></div><span class="day-arrow">↗</span></div><div><p>${p.focus}</p>${active?'<span class="pill">继续训练</span>':last?`<span class="pill done">上次 ${fmtDate(last.date)}</span>`:'<span class="pill">开始训练</span>'}</div></div>`}).join('');app.innerHTML=`<section class="hero"><div class="date-line"><span>训练 · 记录 · 回顾</span><span>${new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'short'}).format(new Date())}</span></div><h1>今天，练一点。</h1><p>按自己的节奏来，稳定完成就是进步。</p></section><div class="section-head"><h2>选择训练</h2><small>每周 3 次力量 + 游泳</small></div><div class="split">${days}</div><div class="notice" style="margin-top:17px"><strong>训练提示</strong><br>大多数力量组保持 RIR 2–3。肩颈轻微不适若逐组加重、出现刺痛或麻木，停止该动作；颈肩疼痛明显高于平时并持续至次日，下次可降低负荷或组数。训练记录仅用于个人追踪，不代替专业评估。</div>`}
function openPlan(id){const p=PLAN.find(x=>x.id===id);if(p){document.querySelector('#modal')?.remove();const el=document.createElement('div');el.id='modal';el.style.cssText='position:fixed;inset:0;background:#14251f70;z-index:15;display:grid;place-items:end center;padding:12px';el.innerHTML=`<div style="background:#fffefa;border-radius:20px;max-width:600px;width:100%;max-height:85vh;overflow:auto;padding:20px"><div class="row"><div><div class="eyebrow">${p.en}</div><h2 style="margin:4px 0">${p.name}</h2></div><button class="text-btn" onclick="document.querySelector('#modal').remove()">关闭</button></div><p class="muted" style="font-size:13px">${p.warmup}</p>${p.items.map(x=>`<div class="exercise-info card"><b>${x.name}</b> <span class="muted">${x.sets} 组 · ${x.reps} 次 · 休息 ${x.rest} 秒</span><details><summary>动作说明与替代</summary><div class="info-section"><b>怎么做：</b>${x.how}</div><div class="info-section"><b>要点：</b>${x.care}</div><div class="info-section"><b>目标：</b>${x.muscles}</div><div class="info-section"><b>替代：</b>${x.alts.join('；')}</div></details></div>`).join('')}<button class="btn wide" onclick="document.querySelector('#modal').remove();startWorkout('${p.id}')">${data.sessions.some(s=>s.planId===p.id&&s.status==='active')?'继续训练':'开始训练'}</button></div>`;el.onclick=e=>{if(e.target===el)el.remove()};document.body.append(el)}}
function renderWorkout(id){const s=data.sessions.find(x=>x.id===id);if(!s){location.hash='#home';return}data.active=s.id;const p=PLAN.find(x=>x.id===s.planId),done=s.exercises.reduce((n,x)=>n+x.sets.filter(y=>y.done).length,0),total=s.exercises.reduce((n,x)=>n+x.sets.length,0);const cards=s.exercises.map((x,idx)=>exerciseCard(x,x.meta||p.items.find(a=>a.id===(x.originId||x.id)),idx)).join('');const isDone=s.status==='done';app.innerHTML=`<button class="nav-back" onclick="location.hash='#home'">← 训练列表</button><div class="eyebrow">${p.en} · ${fmtDate(s.date)}</div><h1 class="workout-title">${p.name}</h1><div class="workout-meta">${p.focus} · ${done}/${total} 组完成</div><div class="progress-wrap"><div class="progress" style="width:${total?done/total*100:0}%"></div></div>${isDone?'<div class="notice">本次训练已打卡。记录仍可查看。</div>':''}<div class="notice"><strong>热身建议</strong><br>${p.warmup}</div>${cards}<div class="card"><h3 style="margin:0 0 12px">训练总结</h3><div class="summary-grid"><div><label>整体感受</label><select onchange="summaryField('effort',this.value)"><option value="">选择</option>${['轻松','合适','偏累'].map(v=>`<option ${s.summary.effort===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label>肩颈疼痛 0–10</label><input type="number" min="0" max="10" inputmode="numeric" value="${esc(s.summary.pain)}" placeholder="—" onchange="summaryField('pain',this.value)"></div><div><label>本次训练</label><div class="muted" style="padding:10px 0;font-size:12px">${done} 组完成</div></div><div class="span3"><label>训练后备注</label><textarea class="note-area" placeholder="今天的整体感受…" onchange="summaryField('note',this.value)">${esc(s.summary.note)}</textarea></div></div></div><button class="btn wide" onclick="finishWorkout('${s.id}')" ${isDone?'disabled':''}>完成训练并打卡</button><button class="btn ghost wide" style="margin-top:9px" onclick="cancelWorkout('${s.id}')">放弃本次训练</button>${s.restUntil?restBox(s):''}`;if(s.restUntil)tick()}
function exerciseCard(x,meta,index){const prev=latestSession(data.sessions.find(s=>s.id===data.active)?.planId)?.exercises.find(a=>a.id===x.id);return `<article class="exercise" id="exercise-${esc(x.id)}"><div class="exercise-head"><div><h3>${esc(x.name)} ${x.skip?'<span class="tag">已跳过</span>':''}</h3><div class="exercise-sub">${esc(meta.muscles)} · 目标 ${x.sets.length} 组 × ${meta.reps} · 目标 RIR 2–3 · 休息 ${meta.rest||0}s</div></div><div class="exercise-tools"><button onclick="showInfo('${x.id}')">说明</button></div></div>${data.permanentNotes[x.id]?`<div class="lastline">长期备注：${esc(data.permanentNotes[x.id])}</div>`:''}${prev?`<div class="lastline">上次 ${fmtDate(prev.date||'')}：${prev.sets.map(a=>a.weight&&a.reps?`${a.weight} kg × ${a.reps}`:'').filter(Boolean).join(' / ')||'有训练记录'}</div>`:''}<div class="set-head"><span>组</span><span>重量 kg</span><span>次数</span><span>RIR</span><span>✓</span></div>${x.sets.map((a,i)=>`<div class="set-row"><span class="set-num">${i+1}</span><input class="field" type="number" inputmode="decimal" min="0" step="0.5" placeholder="kg" value="${esc(a.weight)}" onchange="setField('${x.id}',${i},'weight',this.value)" ${x.skip?'disabled':''}><input class="field" type="number" inputmode="numeric" min="0" placeholder="次" value="${esc(a.reps)}" onchange="setField('${x.id}',${i},'reps',this.value)" ${x.skip?'disabled':''}><input class="field" type="number" inputmode="numeric" min="0" max="10" placeholder="—" value="${esc(a.rir)}" onchange="setField('${x.id}',${i},'rir',this.value)" ${x.skip?'disabled':''}><button class="check ${a.done?'checked':''}" onclick="toggleSet('${x.id}',${i})" aria-label="标记第${i+1}组完成">${a.done?'✓':'○'}</button>${prev?.sets[i]?`<span class="last-mini">上次 ${prev.sets[i].weight||'—'} kg × ${prev.sets[i].reps||'—'}</span>`:''}</div>`).join('')}<div class="exercise-foot"><button class="note-toggle" onclick="toggleNote('${x.id}')">${x.note?'编辑本次备注':'＋ 本次备注'}</button><div><button class="text-btn" onclick="changeSets('${x.id}',-1)">− 组</button><button class="text-btn" onclick="changeSets('${x.id}',1)">＋ 组</button></div></div><textarea id="note-${x.id}" class="note-area" placeholder="本次感受或动作调整" style="display:${x.note||x.showNote?'block':'none'}" onchange="exerciseNote('${x.id}',this.value)">${esc(x.note)}</textarea><label class="note-toggle"><input type="checkbox" ${x.skip?'checked':''} onchange="skipExercise('${x.id}',this.checked)"> 标记跳过</label>${x.skip?`<input class="field" style="margin-top:8px;text-align:left" placeholder="跳过原因（可选）" value="${esc(x.skipReason)}" onchange="skipReason('${x.id}',this.value)">`:''}<details class="exercise-info"><summary>动作说明与替代</summary><div class="info-section"><b>怎么做：</b>${esc(meta.how)}</div><div class="info-section"><b>注意：</b>${esc(meta.care)}</div><div class="info-section"><b>替代：</b>${meta.alts.map((alt,i)=>`<button class="text-btn small" onclick="useAlt('${x.id}',${i})">${esc(alt)}</button>`).join('')}</div></details></article>`}
function fmtDate(d){return d?`${Number(d.slice(5,7))}/${Number(d.slice(8,10))}`:''}
function setField(id,i,key,val){const s=current(),x=s?.exercises.find(a=>a.id===id);if(!x)return;x.sets[i][key]=val;save()}
function toggleSet(id,i){const s=current(),x=s?.exercises.find(a=>a.id===id);if(!x)return;const set=x.sets[i];if(!set.done){set.done=true;const meta=x.meta||PLAN.find(p=>p.id===s.planId).items.find(e=>e.id===(x.originId||x.id));if(meta?.rest){s.restUntil=Date.now()+meta.rest*1000;s.restLabel=x.name}}else set.done=false;save().then(render);}
function changeSets(id,d){const s=current(),x=s.exercises.find(a=>a.id===id);if(d<0&&x.sets.length<=1){toast('至少保留一组');return}if(d>0)x.sets.push({weight:x.sets.at(-1)?.weight||'',reps:'',rir:''});else x.sets.pop();save().then(render)}
function toggleNote(id){document.querySelector(`#note-${CSS.escape(id)}`).style.display='block';document.querySelector(`#note-${CSS.escape(id)}`).focus()}
function exerciseNote(id,v){const x=current().exercises.find(a=>a.id===id);x.note=v;save()}
function skipExercise(id,v){const x=current().exercises.find(a=>a.id===id);x.skip=v;if(v)x.sets.forEach(a=>a.done=false);save().then(render)}
function skipReason(id,v){current().exercises.find(a=>a.id===id).skipReason=v;save()}
async function useAlt(id,n){const s=current(),x=s.exercises.find(a=>a.id===id),base=PLAN.find(p=>p.id===s.planId).items.find(a=>a.id===(x.originId||x.id));x.originId??=x.id;x.id=`${x.originId}-alt-${n}`;x.name=base.alts[n];x.meta={...base,name:x.name};await save();render();toast('已切换动作；替代动作历史单独记录')}
function showInfo(id){document.querySelector(`#exercise-${CSS.escape(id)} details`).open=true}
function summaryField(k,v){current().summary[k]=v;save()}
async function finishWorkout(id){const s=data.sessions.find(x=>x.id===id);if(!s)return;const pending=s.exercises.flatMap(x=>x.sets).filter(x=>x.weight!==''||x.reps!=='').filter(x=>!x.done).length;if(pending&&!confirm(`还有 ${pending} 组填写了记录但未标完成。仍然打卡吗？`))return;s.status='done';s.completedAt=Date.now();s.exercises.forEach(x=>{x.date=s.date});s.restUntil=null;await save();toast('训练已完成并记录到日历');render()}
function cancelWorkout(id){if(!confirm('确定删除这次尚未完成的训练记录吗？'))return;data.sessions=data.sessions.filter(s=>s.id!==id);data.active=null;save().then(()=>location.hash='#home')}
function restBox(s){return `<div class="restbox"><div><small>${esc(s.restLabel)} · 休息</small><br><strong id="rest-time">--:--</strong></div><span id="rest-state">计时中</span><div class="rest-actions"><button onclick="adjustRest(-30)">−30 秒</button><button onclick="adjustRest(30)">+30 秒</button><button onclick="skipRest()">跳过休息</button></div></div>`}
function tick(){const s=current();if(!s?.restUntil)return;const sec=Math.max(0,Math.ceil((s.restUntil-Date.now())/1000));const el=document.querySelector('#rest-time');if(el)el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(!sec){if(!s.restNotified){s.restNotified=true;save();document.querySelector('#rest-state')?.replaceChildren(document.createTextNode('休息结束'));if(navigator.vibrate)navigator.vibrate([150,80,150])}return}if(!timerId)timerId=setTimeout(()=>{timerId=null;tick()},500)}
function adjustRest(n){const s=current();if(s){s.restUntil=Math.max(Date.now(),s.restUntil+n*1000);s.restNotified=false;save();tick()}}
function skipRest(){const s=current();if(s){s.restUntil=null;save().then(render)}}
function renderCalendar(){const y=viewMonth.getFullYear(),m=viewMonth.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),records=new Map();data.sessions.filter(s=>s.status==='done').forEach(s=>{if(!records.has(s.date))records.set(s.date,[]);records.get(s.date).push(s)});const cells=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const iso=localISO(d),inside=d.getMonth()===m;return `<button class="cal-day ${inside?'':'dim'} ${iso===today()?'today':''} ${iso===selectedDate?'selected':''} ${records.has(iso)?'has-record':''}" onclick="selectDate('${iso}')">${d.getDate()}</button>`}).join('');const picked=records.get(selectedDate)||[];app.innerHTML=`<div class="hero"><div class="eyebrow">训练记录</div><h1>训练日历</h1><p>点选日期查看训练打卡。</p></div><div class="calendar"><div class="cal-head"><button onclick="changeMonth(-1)">‹</button><strong>${y} 年 ${m+1} 月</strong><button onclick="changeMonth(1)">›</button></div><div class="cal-grid">${'日一二三四五六'.split('').map(x=>`<div class="dow">${x}</div>`).join('')}${cells}</div><div class="legend"><span><i></i>已完成训练</span><span>绿色圆点框为今天</span></div></div><div class="section-head"><h2>${selectedDate===today()?'今天':selectedDate}</h2><small>${picked.length} 次训练</small></div>${picked.length?picked.map(sessionCard).join(''):'<div class="empty card">这一天没有训练打卡。</div>'}`}
function sessionCard(s){const p=PLAN.find(x=>x.id===s.planId),count=s.exercises.reduce((n,x)=>n+x.sets.filter(a=>a.done).length,0);return `<div class="card" onclick="openSession('${s.id}')" style="cursor:pointer"><div class="row"><strong>${p.name}</strong><span class="pill done">已完成</span></div><p class="muted" style="font-size:12px">${p.focus} · ${count} 组完成 ${s.summary.pain!==''?`· 肩颈 ${s.summary.pain}/10`:''}</p><div class="muted" style="font-size:11px">${s.summary.effort||''} ${esc(s.summary.note||'')}</div></div>`}
function selectDate(d){selectedDate=d;renderCalendar()}function changeMonth(n){viewMonth=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+n,1);renderCalendar()}
function openSession(id){data.active=id;location.hash='#workout/'+id}
function renderHistory(){const sessions=data.sessions.filter(s=>s.status==='done').sort((a,b)=>b.date.localeCompare(a.date));const choices=PLAN.flatMap(p=>p.items).filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);app.innerHTML=`<div class="hero"><div class="eyebrow">回看进步</div><h1>动作历史</h1><p>按动作查看过去的组数、重量与次数。</p></div><label class="fieldlabel">选择动作</label><select class="field" style="text-align:left" id="historyExercise" onchange="historyExercise(this.value)"><option value="">选择一个动作</option>${choices.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><div id="historyResults" class="history-detail"><div class="empty card">选择动作后查看训练记录。</div></div><div class="section-head"><h2>最近训练</h2><small>${sessions.length} 次完成</small></div>${sessions.slice(0,6).map(sessionCard).join('')||'<div class="empty card">完成第一次训练后，记录会显示在这里。</div>'}`}
function historyExercise(id){const sessions=data.sessions.filter(s=>s.status==='done'&&s.exercises.some(x=>x.id===id)).sort((a,b)=>b.date.localeCompare(a.date));const name=PLAN.flatMap(p=>p.items).find(x=>x.id===id)?.name;document.querySelector('#historyResults').innerHTML=`<h3>${esc(name)}</h3>${sessions.length?`<div class="history-list">${sessions.map(s=>{const x=s.exercises.find(a=>a.id===id),sets=x.sets.filter(a=>a.weight!==''||a.reps!=='');const best=sets.reduce((b,a)=>Number(a.weight)>Number(b.weight)?a:b,sets[0]||{}),volume=sets.reduce((n,a)=>n+(Number(a.weight)||0)*(Number(a.reps)||0),0);return `<div class="history-row"><div class="row"><strong>${fmtDate(s.date)} · ${s.date}</strong><span class="tag">${sets.filter(a=>a.done).length}/${x.sets.length} 组完成</span></div><p>最佳 ${best.weight||'—'} kg × ${best.reps||'—'} · 总训练量 ${volume?volume.toLocaleString()+' kg':'—'}</p>${x.note?`<p>${esc(x.note)}</p>`:''}</div>`}).join('')}</div>`:'<div class="empty card">这个动作还没有完成记录。</div>'}`}
function renderSettings(){const defaults=PLAN.flatMap(p=>p.items).map(x=>`<div class="setting-row"><h3>${esc(x.name)}</h3><p>默认 ${x.sets} 组 · ${x.reps} 次 · 休息 ${x.rest} 秒</p><div style="display:flex;align-items:center;gap:9px;margin-top:9px"><button class="btn secondary small" onclick="defaultSets('${x.id}',-1)">−</button><b>${data.defaults[x.id]??x.sets} 组</b><button class="btn secondary small" onclick="defaultSets('${x.id}',1)">＋</button><button class="text-btn small" onclick="resetSets('${x.id}')">恢复计划值</button></div><label class="fieldlabel">长期备注</label><textarea class="note-area" placeholder="下次训练也会显示" onchange="permanentNote('${x.id}',this.value)">${esc(data.permanentNotes[x.id]||'')}</textarea></div>`).join('');app.innerHTML=`<div class="hero"><div class="eyebrow">偏好与数据</div><h1>设置</h1><p>数据保存在当前浏览器，可随时导出备份。</p></div><div class="card"><div class="row"><div><b>数据备份</b><div class="muted" style="font-size:12px;margin-top:4px">导出完整记录为 JSON，换设备前请先备份。</div></div><button class="btn secondary small" onclick="backup()">导出</button></div><div class="row" style="margin-top:14px"><div><b>恢复数据</b><div class="muted" style="font-size:12px;margin-top:4px">从本地 JSON 备份文件导入。</div></div><button class="btn secondary small" onclick="document.querySelector('#importFile').click()">导入</button></div></div><div class="notice">所有训练和健康相关记录只存储在本设备浏览器的 IndexedDB 中。清除浏览器数据可能导致记录丢失；定期导出 JSON 备份。</div><div class="section-head"><h2>默认组数</h2><small>调整后用于新训练</small></div><div class="card">${defaults}</div><div class="section-head"><h2>关于计划</h2></div><div class="notice">拉日细节在原对话缓存中不完整，目前的拉日动作是保守的初始建议，可以按实际器械和身体反馈调整。动作可通过训练页的说明查看目标、要点与替代方案。此工具不提供医疗诊断。</div>`}
function defaultSets(id,d){const item=PLAN.flatMap(p=>p.items).find(x=>x.id===id);data.defaults[id]=Math.min(8,Math.max(1,(data.defaults[id]??item.sets)+d));save().then(renderSettings)}function resetSets(id){delete data.defaults[id];save().then(renderSettings)}function permanentNote(id,v){data.permanentNotes[id]=v;save()}
async function backup(){await save();const blob=new Blob([JSON.stringify({app:'练习簿',schemaVersion:1,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`练习簿备份-${today()}.json`;a.click();URL.revokeObjectURL(url);toast('备份文件已导出')}
async function importBackup(ev){const file=ev.target.files?.[0];if(!file)return;try{const obj=JSON.parse(await file.text());const incoming=obj.data;if(!incoming||!Array.isArray(incoming.sessions)||typeof incoming.defaults!=='object')throw Error('备份格式不正确');if(!confirm(`将导入 ${incoming.sessions.length} 条训练记录，并替换本设备当前数据。继续吗？`))return;data={sessions:incoming.sessions,defaults:incoming.defaults||{},permanentNotes:incoming.permanentNotes||{},active:incoming.active||null};await save();toast('数据已恢复');render()}catch(e){alert(`无法导入：${e.message}`)}finally{ev.target.value=''}}
function installApp(){if(deferredInstall){deferredInstall.prompt();deferredInstall=null;document.querySelector('#installBtn').hidden=true}else toast('请使用浏览器菜单中的“添加到主屏幕”')}
let toastTimeout;function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('show'),2200)}
init();
